### ISSUE TITLE
fail to precompile / install on jupyterhub

### ISSUE THREAD

**Issue by gaelforget** [GenericMappingTools/GMT.jl#1095]
I have been trying to use `GMT.jl` within a containerized environment but get the error below.

<img width="855" alt="Screenshot 2023-01-03 at 9 35 15 AM" src="https://user-images.githubusercontent.com/20276764/210378184-d15b4b60-f352-411d-9574-0da71089c697.png">

To reproduce this error :

- `docker run -p 8888:8888 jupyter/datascience-notebook:latest`
- once browser window is open, start terminal, Julia, and `using GMT`

...

**Comment by gaelforget** [comment]
I tried a couple more things with this `Dockerfile` :

```
FROM jupyter/datascience-notebook:latest

USER root

RUN apt-get install -y --no-install-recommends gmt
RUN apt-get install -y --no-install-recommends gmt-dcw gmt-gshhg
RUN apt-get install -y --no-install-recommends ghostscript

USER ${NB_USER}

RUN julia -e "import Pkg; Pkg.add(\"GMT\"); Pkg.precompile()"
```

which follows directions from the `GMT` docs for the `apt-get` part.

This errors as 

<img width="952" alt="Screenshot 2023-01-03 at 9 43 57 AM" src="https://user-images.githubusercontent.com/20276764/210379957-92c80dce-9157-412a-b23e-efa5c584bf20.png">

which I think indicates that `apt-get` does not carry `gmt`. Is that right?

**Comment by gaelforget** [comment]
Could be related to https://github.com/GenericMappingTools/GMT.jl/issues/1052 and https://github.com/GenericMappingTools/GMT.jl/issues/1049

**Comment by joa-quim** [comment]
Hi,

First I thought *Ui, can't help. Know nothing about containers* but than I saw that infamous ``libstdc++`` error that gave so many headaches during half an year. The problem is on the Linux side that is so light on dependency breaking. GCC12 introduced a new ``libstdc++`` lib that is incompatible with Julia versions up until 1.8.3. So you need to have at at least Julia 1.8.4

**Comment by gaelforget** [comment]
Thanks for getting back so quickly!

> Know nothing about containers

You likely use containers for your CI on github and various other things like binder or jupyterlab. I am no expert either but it's really useful to learn basics imho. In case that's of interest, we made this video as prep for the JuliaEO workshop. 

https://youtu.be/daNrJhPPgWg

> GCC12 introduced a new `libstdc++` lib that is incompatible with Julia versions up until 1.8.3. So you need to have at at least Julia 1.8.4

Too bad. I was just taking a look in context of a workshop taking place next week where we are using Docker & 1.8.3 -- https://aircentre.github.io/JuliaEO/

> EDIT: Or install GMT independently in the container so to avoid the automatic installation done via Conda (this is the one that uses a GMT GCC12 build)

This failed for me too though. See https://github.com/GenericMappingTools/GMT.jl/issues/1095#issuecomment-1369852643

**Comment by joa-quim** [comment]
> which I think indicates that apt-get does not carry gmt. Is that right?

A quick answer to this. Those VMs are often based on Ubuntu and this distro is, by default, incredibly dumb on providing updated versions. The [GMT site](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md) has info on how to install/build GMT

**Comment by joa-quim** [comment]
Another possibility. The [CI tests](https://github.com/GenericMappingTools/GMT.jl/blob/master/.github/workflows/ci.yml) always build GMT from source. Could chunks of that GH-Action be extracted into your build env?

**Comment by gaelforget** [comment]
> 

Could work. Thanks for the pointers

**Comment by gaelforget** [comment]
> 



> Another possibility. The [CI tests](https://github.com/GenericMappingTools/GMT.jl/blob/master/.github/workflows/ci.yml) always build GMT from source. Could chunks of that GH-Action be extracted into your build env?

Could work. Thanks for the pointers

**Comment by joa-quim** [comment]
GMT_jll artifact is now used, so these problems should have gone.
