### ISSUE TITLE
unable to use GMT.jl 

### ISSUE THREAD

**Issue by igaszczesniak** [GenericMappingTools/GMT.jl#1098]
I have been trying to use GMT.jl but get the error below. I installed the package via Homebrew with dependencies (Ghostscript, graphicsmagick, ffmpeg). I am using Mac.

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/97889272/211006924-bd14a989-7654-44ff-a77f-1d1f5662df57.png">

**Comment by joa-quim** [comment]
Hi, sorry to hear that. It looks like the build step was not run and hence the ``.../deps/deps.jl`` file was not created.
Can you try it from the REPL instead of doing it from Jupyter?

Note, the GMT documentation is build with Franklin and uses Homebrew to build it (see the [GH-action here](https://github.com/GenericMappingTools/GMTjl_doc/blob/master/.github/workflows/deploy.yml#L24)) so I know that it works with a Homebrew GMT installation.

**Comment by igaszczesniak** [comment]
Hi Joaquim, thank you so much! Indeed, deps.jl file was missing. 
I was using REPL ] add GMT and didn't work. It only worked after I run: 
<img width="451" alt="image" src="https://user-images.githubusercontent.com/97889272/211030790-782d3655-1c95-4256-b4e8-3372c95a4d22.png">

**Comment by joa-quim** [comment]
Well, for one side good that you found a solution but for the other side that's a convoluted one. I must find out more about this failure. Does this mean that the ``Pkg.build("GMT")`` was not run at install time?

**Comment by igaszczesniak** [comment]
> Well, for one side good that you found a solution but for the other side that's a convoluted one. I must find out more about this failure. Does this mean that the `Pkg.build("GMT")` was not run at install time?

I was trying the following:
In Jupyter, using Pkg; Pkg.add("GMT") - didn't work
In REPL, ] add GMT - didn't work 
In Homebrew, brew install GMT; brew install dependencies - didn't work 

I didn't use Pkg.build("GMT") at any stage

**Comment by joa-quim** [comment]
> I didn't use Pkg.build("GMT") at any stage

We are not supposed to run it ourselves but when things fail Julia gives us that as a hint to try to find why compilation failed.

> In REPL, ] add GMT - didn't work

That is the one that should absolutely work.

**Comment by joa-quim** [comment]
Really don't know. Unix is such a strange world. I resurrected my old Mac (a 2014 model), installed GMT via homebrew, Julia with Juliaup and all worked fine.
