### ISSUE TITLE
Setting the z range in `bar3` plot.

### ISSUE THREAD

**Issue by LeeoBianchi** [GenericMappingTools/GMT.jl#1137]
Hi! Amazing package!

I am trying to plot a 3-d histogram through `bar3` with the z-axis starting from 0.0. Is this done through the keyword setting `base = 0.0`? It seem to get ignored!

`
G = GMT.mat2grid(randn(5, 6))
cmap = grd2cpt(G);
bar3(G,
     lw=:thinnest,
     color=cmap,
     base=0.0,
     figname="prova.png")
`

Thank you!

**Comment by joa-quim** [comment]
> Hi! Amazing package!

Thanks, I agree 😃 

Humm, it works for me

```
G = GMT.mat2grid(randn(5, 6));
cmap = grd2cpt(G);
bar3(G, lw=:thinnest, color=cmap, base=0.0, figname="prova.png")
```
![prova](https://user-images.githubusercontent.com/537321/224506312-da15548f-9faa-4c38-a55f-776e910f815a.png)

**Comment by joa-quim** [comment]
Sorry, I overlooked the ``base=0.0`` part.

**Comment by joa-quim** [comment]
https://forum.generic-mapping-tools.org/t/is-this-a-plot3d-s0-bug/3748

**Comment by joa-quim** [comment]
Fixed in https://github.com/GenericMappingTools/GMT.jl/pull/1138

**Comment by joa-quim** [comment]
No, that is clearly a bug. ``region`` and ``limits`` are synonyms.

**Comment by LeeoBianchi** [comment]
> No, that is clearly a bug. `region` and `limits` are synonyms.

Hmm okay, then definitely a bug! 

Moreover, when I am specifying both `region` and `limits`, the `base` keyword becomes unnecessary.
Here is the code to reproduce it:
```
G = GMT.mat2grid(randn(5, 6).+300, x=[10 20 30 40 50 60], y=[1 2 3 4 5])
cmap = grd2cpt(G);
bar3(G,
     lw=:thinnest,
     color=cmap,
     base="0.0",
     region = [5 65 0.5 5.5 0 600],
     limits = (5, 65, 0.5, 5.5, 0, 600),
     xaxis=(annot=10, ticks=:auto, label="X"),
     yaxis=(annot=1, ticks=:auto, label="Y"),
     zaxis=(annot=:auto, ticks=:auto, label="Z"),
     show = true,
     figsize = (10.5, 9),
     figname="test.png"
     )
```

**Comment by joa-quim** [comment]
Fixed ``limits/region`` issue in https://github.com/GenericMappingTools/GMT.jl/pull/1139

Yes, limiting with ``region`` to positive only is another way of setting ``base=0.0``

**Comment by LeeoBianchi** [comment]
> Fixed `limits/region` issue in #1139

Amazing!
 
> Yes, limiting with `region` to positive only is another way of setting `base=0.0`

Yes, that makes sense.

One more thing: what if I wanted to put custom annotations on one of the axis, but leaving the ticks where they are? I haven't found a way to make this work.

In particular in my case I would like a 2 in place of  the 0. But if I try to use the `xticks` keyword I get all the ticks compressed around 0 and the Z axis disappears. Am I doing something wrong?

```
G = GMT.mat2grid(randn(5, 7).+300, x=[0 10 20 30 40 50 60], y=[1 2 3 4 5])
cmap = grd2cpt(G);
bar3(G,
     lw=:thinnest,
     color=cmap,
     region = [-5 65 0.5 5.5 0 600],
     limits = (-5, 65, 0.5, 5.5, 0, 600),
     xticks=(2, 10, 20, 30, 40, 50, 60),
     show = true,
     figsize = (10.5, 9),
     figname="prova.png"
     )
```

![prova](https://user-images.githubusercontent.com/71835745/225014560-cf92597b-b13b-4983-9576-5d9a5d492851.png)

Cheers,
Leo

**Comment by joa-quim** [comment]
You can do this but there must be a better (cleaner to the reader) way

```
bar3(G, lw=:thinnest, color=cmap, region = [-5 65 0.5 5.5 0 600], xaxis=(custom=(pos=[2, 10, 20, 30, 40, 50, 60], type=["a","a","a","a","a","a","a"]),), yaxis=:a, show=1)
```
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/225128471-118f0e92-ad1d-4be2-9c7c-f30c4a4a6096.png)

**Comment by joa-quim** [comment]
Simpler this way
```
bar3(G, lw=:thinnest, color=cmap, region = [-5 65 0.5 5.5 0 600], xticks=([2, 10, 20, 30, 40, 50, 60], ("2","10","20","30","40","50","60")), show=1)
```

**Comment by LeeoBianchi** [comment]
Amazing, it worked! Thank you so much.

Last question, I promise: is there a way to show a grid (or simply thin horizontal lines for each tick) in the background, on the zy plane, for instance?

Leo

**Comment by joa-quim** [comment]
No problem with questions, only that I would prefer that they are made in the GMT forum.

The answer is *off course* yes but needs to dig from the (*frame*) docs to find the right option.

**Comment by joa-quim** [comment]
Can we close this?

**Comment by LeeoBianchi** [comment]
Sure, thanks for all the useful tips!
