### ISSUE TITLE
Installation/update failed on a multi-user system

### ISSUE THREAD

**Issue by melodyjulia** [GenericMappingTools/GMT.jl#1154]
If several users use GMT.jl on a same Linux system, /tmp/GMTjl_tmp.ps and /tmp/GMTjl_custom_px.txt files were created by the first user during the installation and the created files were left there. Then, when another user trys to install GMT.jl, the following errors prompt and the installation would fail:

PSL: PSL_fopen error: Unable to open file /tmp/GMTjl_tmp.ps with mode w!
psxy [ERROR]: Cannot open /tmp/GMTjl_tmp.ps with mode w
LoadError: SystemError: opening file "/tmp/GMTjl_custom_px.txt": Permission denied

To install GMT.jl successfully, the previous user has to remove the above two files manually after installation.

The test environment is CentOS Linux release 7.4.1708 (Core), Julia 1.8.5 and GMT.jl v0.44.8.

**Comment by joa-quim** [comment]
Hmm, I hadn't thought on that. I thought that files in /tmp would always be re-writable for all. Will have to think in a solution. Thanks for reporting this. 

> To install GMT.jl successfully, the previous user has to remove the above two files manually after installation.

But upon installation no files are written to /tmp so why would that be?

**Comment by melodyjulia** [comment]
The two temporary files created during a previous installation/update have to be deleted by the previous user installing it, then a subsequent user can do a new installation/update.

Actually, GMT.jl sometimes creates /tmp/GMTjl_tmp.ps, this hinders other users on the same system from using GMT.jl properly.

**Comment by joa-quim** [comment]
While I don't get a permanent solution, a workaround is to re-declare the default name. The global variable ``GMT.PSname[1]`` holds that name so if you do
```
GMT.PSname[1] = "/tmp/GMT_tmp.ps";
```
it should let you create plots again. However, this does not solve the issue with files created by custom axes.

**Comment by melodyjulia** [comment]
Thanks very much. This solves my problem!

**Comment by joa-quim** [comment]
Hi, it would be nice if you could test the master version. I've implemented a new mechanism where the temporary file names include the username so that we should not expect any more file name clashes and permissions problems. It seems to be working fine but I only tested in on single-user systems.

**Comment by melodyjulia** [comment]
There's no name clashes for /tmp/GMTjl_tmp.ps and /tmp/GMTjl_tmp.png files now. But I noticed another file name clash: /tmp/GMTjl_custom_p_x.txt

Btw, I setup a new account to install GMT.jl.  There's a similar file name clash and permission problem from Conda package when using Conda to install "gmt" package manually. A conda installation file would be left on system (/tmp/installer.sh) if another user installing GMT.jl, then later users won't be able to install "gmt" package.

**Comment by joa-quim** [comment]
OM, I fixed the first case. That ``GMTjl_custom_p_x.txt`` got generated at the ``SnoopPrecompile`` stage when the username is not yet known. Now I simply delete is also inside the ``SnoopPrecompile`` block.

Regarding the Conda script, it soon will no longer bother because we'll drop the Conda install and replace it by a ``GMT_jll``.

**Comment by melodyjulia** [comment]
> OK, I fixed the first case. That `GMTjl_custom_p_x.txt` got generated at the `SnoopPrecompile` stage when the username is not yet known. Now I simply delete is also inside the `SnoopPrecompile` block.
> 
> Regarding the Conda script, it soon will no longer bother because we'll drop the Conda install and replace it by a `GMT_jll`.

This is awesome. Looking forward to using it asap.

**Comment by joa-quim** [comment]
Merged GMT_jll on master

**Comment by melodyjulia** [comment]
> Merged GMT_jll on master

I tested it and it works like a charm.
