### ISSUE TITLE
Problem to specify the position of a legend

### ISSUE THREAD

**Issue by melodyjulia** [GenericMappingTools/GMT.jl#1167]
The following way to specify the position of a legend doesn't work:
```
lines(1:12, 1:12, figsize=(6,4), legend=(label="data",position=(inside=:LT,width=1.5),fontsize=3), show=true)
```

**Comment by joa-quim** [comment]
OK, there some inconsistencies and I would like that the for you used works, but note that it's not documented. You are probably following the example at https://www.generic-mapping-tools.org/GMTjl_doc/examples/legends/01_legends/#apples_oranges but you need to understand that there are *two legends* here. One is the module *legend* that is used in the apples example and the other *legend* is a *keyword=value* option of the ``plot`` module. Well, deep inside there is only one *legend*, the module, and the *keyword=value* pair is used to simplify its usage. The documented way is to use ``pos=:LT``, though the following do what you want even though the ``width=1.5`` is not mentioned in the ``plot`` module docs. Again, some things need to be tuned out. 

```
lines(1:12, 1:12, legend=(label="data",position=(pos=:LT, width=1.5), fontsize=3), show=true)
```

**Comment by melodyjulia** [comment]
Thanks. It works!

**Comment by joa-quim** [comment]
Yes, but I'm not sure I can let it work. Too late here. I'll let you know how this will end up.

**Comment by melodyjulia** [comment]
Actually, I also tried the following and it doesn't work:
```
lines(1:12, 1:12, legend="data")
legend!(position=(pos=:LT, width=1.5), fontsize=3, show=true)
```
I thought it's equivalent to the following one-line form:
```
lines(1:12, 1:12, legend=(label="data",position=(pos=:LT, width=1.5), fontsize=3), show=true)
```

**Comment by joa-quim** [comment]
No, that cannot work without further data. When using the ``legend`` module, instead of the *keyword=value* pair, one has to provide all needed data. Like in the example https://www.generic-mapping-tools.org/GMTjl_doc/documentation/modules/legend/index.html#legend

**Comment by joa-quim** [comment]
Fixed this things (I think) in ``master``. These now work and we can also plot the legend outside of the figure in a simple way (before, that was tricky to do right)

```
lines(1:12, 1:12, legend=(label="data",position=(outside=true,anchor=:TR)), show=true)

# or

lines(1:12, 1:12, legend=(label="data", pos=:MC), show=true)
```

Note that ``position=(pos=:LT, width=1.5)`` now doesn't work.

**Comment by melodyjulia** [comment]
Thanks. The "outside" keyword works now.
```position=(pos=:LT, width=1.5)``` works in v0.44.8 version.
