### ISSUE TITLE
Precompilation issue on mac

### ISSUE THREAD

**Issue by boriskaus** [GenericMappingTools/GMT.jl#1234]
Im receiving the following error on Mac (Julia version 1.9.0), while installing a fresh version of `1.3.3` (forcing it to use the `GMT_jll` binary by ensuring that the `gmt` executable is not available on the command line.
```Julia
julia> using GMT
[ Info: Precompiling GMT [5752ebe1-31b9-557e-87aa-f909b540aa54]
[Session GMT (1)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
makecpt [ERROR]: File /workspace/destdir/share/matlab/jet.cpt was not found
makecpt [ERROR]: Cannot find file /workspace/destdir/share/matlab/jet.cpt
makecpt [ERROR]: File /workspace/destdir/share/matlab/jet.cpt not found
[Session GMT (2)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
ERROR: LoadError: Something went wrong when calling the module. GMT error number = 16
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] gmt(::String)
    @ GMT ~/.julia/packages/GMT/yn1Hd/src/gmt_main.jl:161
  [3] make_color_column_(d::Dict{Symbol, Any}, cmd::String, len_cmd::Int64, N_args::Int64, n_prev::Int64, is3D::Bool, got_Ebars::Bool, arg1::GMT.GMTdataset{Float64, 2}, arg2::Nothing, mz::Nothing, n_col::Int64)
    @ GMT ~/.julia/packages/GMT/yn1Hd/src/psxy.jl:1009
  [4] make_color_column(d::Dict{Symbol, Any}, cmd::String, opt_i::String, len_cmd::Int64, N_args::Int64, n_prev::Int64, is3D::Bool, got_Ebars::Bool, bar_ok::Bool, bar_fill::Vector{String}, arg1::GMT.GMTdataset{Float64, 2}, arg2::Nothing)
    @ GMT ~/.julia/packages/GMT/yn1Hd/src/psxy.jl:963
  [5] common_plot_xyz(::String, ::GMT.GMTdataset{Float64, 2}, ::String, ::Bool, ::Bool, ::Pair{Symbol, Any}, ::Vararg{Pair{Symbol, Any}})
    @ GMT ~/.julia/packages/GMT/yn1Hd/src/psxy.jl:199
  [6] plot(arg1::Matrix{Float64}; first::Bool, kw::Base.Pairs{Symbol, Any, NTuple{7, Symbol}, NamedTuple{(:marker, :lc, :ls, :lw, :C, :colorbar, :Vd), Tuple{Symbol, Symbol, Symbol, Int64, Symbol, Bool, Int64}}})
    @ GMT ~/.julia/packages/GMT/yn1Hd/src/plot.jl:122
  [7] plot
    @ ~/.julia/packages/GMT/yn1Hd/src/plot.jl:101 [inlined]
  [8] macro expansion
    @ ~/.julia/packages/GMT/yn1Hd/src/GMT.jl:309 [inlined]
  [9] top-level scope
    @ ~/.julia/packages/PrecompileTools/0yi7r/src/workloads.jl:136
 [10] include
    @ ./Base.jl:457 [inlined]
 [11] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2010
 [12] top-level scope
    @ stdin:2
in expression starting at /Users/kausb/.julia/packages/GMT/yn1Hd/src/GMT.jl:1
in expression starting at stdin:2
ERROR: Failed to precompile GMT [5752ebe1-31b9-557e-87aa-f909b540aa54] to "/Users/kausb/.julia/compiled/v1.9/GMT/jl_rYiLva".
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:2260
 [3] compilecache
   @ ./loading.jl:2127 [inlined]
 [4] _require(pkg::Base.PkgId, env::String)
   @ Base ./loading.jl:1770
 [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
   @ Base ./loading.jl:1625
 [6] macro expansion
   @ ./loading.jl:1613 [inlined]
 [7] macro expansion
   @ ./lock.jl:267 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1576
```
Any idea on why it would even want to look for a directory `/workspace/destdir/share/matlab/` which does not exist on my system? Interestingly, GMT was working fine last week or so.
Suggestions are very welcome!

**Comment by joa-quim** [comment]
Will try to find more tomorrow when getting back to computer. 

The /share/matlab part is not strange. That’s where GMT stores the jet.cpt file.

**Comment by boriskaus** [comment]
`/workspace/destdir` does exist on my machine, but why would GMT think that the data is stored there? What is the default directory of using `GMT_jll`?

**Comment by joa-quim** [comment]
@PaulWessel do you have any idea on why GMT would try to search in such a directory?

The ``share`` directory can be set via a ``GMT6_SHAREDIR`` env variable but unless you had that set previously I don't see how that env var could have been set  by Julia. 
You can find (otherwise something very wrong must have occured) the GMT share directory under ``...\.julia\artifacts\..hash..\share`` and that's what should have been attempted.

Can you try to use the ``GMT_jll gmt`` executable to run
```
gmt makecpt -Cjet -Vd
``` 
for me (on command line) it prints:
```
C:\v>gmt makecpt -Cjet -Vd
unknown [DEBUG]: Revised options: -Cjet -Vd
makecpt [INFORMATION]: Prepare CPT via the master file jet
makecpt [DEBUG]: Look for file jet in C:/Users/j/.gmt
makecpt [DEBUG]: Look for file jet in C:/Users/j/.gmt/cache
makecpt [DEBUG]: Look for file jet in C:/Users/j/.gmt/server
makecpt [DEBUG]: GMT: 0. Will try to find subdir=cpt stem = matlab/jet suffix=.cpt
makecpt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
makecpt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR C:/Users/j/.gmt
makecpt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir C:/Users/j/.gmt/cpt
makecpt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir C:/progs_cygw/GMTdev/gmt5/master/share/cpt
makecpt [DEBUG]: Given full path to file C:/progs_cygw/GMTdev/gmt5/master/share/cpt/matlab/jet.cpt
makecpt [DEBUG]: Found readable file C:/progs_cygw/GMTdev/gmt5/master/share/cpt/matlab/jet.cpt
...
```

**Comment by PaulWessel** [comment]
Worklin on +p - dumb bug.


You have to sort through the shits here also:

*(base) ***@***.***:~-> gmt makecpt -Cjet -Vd*

*gmt [DEBUG]: GMT_Create_Session: Terminal width = 172*

*gmt [DEBUG]: Obtained the ppid from parent: 83829*

*gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl*

*gmt [DEBUG]: GMT->session.SHAREDIR =
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share*

*gmt [DEBUG]: GMT->session.HOMEDIR = /Users/pwessel*

*gmt [DEBUG]: GMT->session.USERDIR = /Users/pwessel/.gmt [detected]*

*gmt [DEBUG]: GMT->session.CACHEDIR = /Users/pwessel/.gmt/cache [detected]*

*gmt [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem =
PSL_custom_fonts suffix=.txt*

*gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir*

*gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /Users/pwessel/.gmt*

*gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir
/Users/pwessel/.gmt/postscriptlight*

*gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share/postscriptlight*

*gmt [DEBUG]: GMT: 5. gmt_getsharepath trying SHAREDIR
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share*

*gmt [DEBUG]: GMT: 6. gmt_getsharepath failed*

*gmt [DEBUG]: Map distance calculation will be Cartesian*

*gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl*

*gmt [DEBUG]: Enter: New_PSL_Ctrl*

*gmt [DEBUG]: Exit:  New_PSL_Ctrl*

*gmt [DEBUG]: Enter: gmt_manage_workflow*

*gmt [DEBUG]: Exit : gmt_manage_workflow*

*gmt [DEBUG]: Enter: PSL_beginsession*

*gmt [DEBUG]: Exit : PSL_beginsession*

*gmt [DEBUG]: Enter: PSL_setdefaults*

*gmt [DEBUG]: Exit : PSL_setdefaults*

*gmt [DEBUG]: Enter: gmtlib_io_init*

*gmt [DEBUG]: Exit : gmtlib_io_init*

*gmt [DEBUG]: Enter: gmt_hash_init*

*gmt [DEBUG]: Exit:  gmt_hash_init*

*gmt [DEBUG]: Enter: gmt_hash_init*

*gmt [DEBUG]: Exit:  gmt_hash_init*

*gmt [DEBUG]: Enter: gmt_reload_settings*

*gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty*

*gmt [DEBUG]: Look for file /Users/pwessel/gmt.conf*

*gmt [DEBUG]: Look for file /Users/pwessel/.gmt/gmt.conf*

*gmt [DEBUG]: Look for file /Users/pwessel/.gmt/server/gmt.conf*

*gmt [DEBUG]: Look for file /Users/pwessel/.gmt/cache/gmt.conf*

*gmt [DEBUG]: Could not find file gmt.conf*

*gmt [DEBUG]: Exit:  gmt_reload_settings*

*gmt [DEBUG]: Enter: gmtlib_plot_C_format*

*gmt [DEBUG]: Exit:  gmtlib_plot_C_format*

*gmt [DEBUG]: Enter: gmtinit_get_history*

*gmt [DEBUG]: Enter: gmt_hash_init*

*gmt [DEBUG]: Exit:  gmt_hash_init*

*gmt [DEBUG]: Exit:  gmtinit_get_history*

*gmt [DEBUG]: Initialize FFTW with 10 threads.*

*gmt [DEBUG]: GMT_Create_Session initialized GMT structure*

*gmt [DEBUG]: Loading core GMT shared library: libgmt.dylib*

*gmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.dylib*

*gmt [DEBUG]: Loading GMT plugins from:
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/gmt6/lib/gmt/plugins*

*gmt [DEBUG]: Shared Library # 1 (supplements). Path =
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/gmt6/lib/gmt/plugins/supplements.so*

*gmt [DEBUG]: Revised options: -Cjet -Vd*

*makecpt [INFORMATION]: Prepare CPT via the master file jet*

*makecpt [DEBUG]: Look for file jet in /Users/pwessel/.gmt*

*makecpt [DEBUG]: Look for file jet in
/Users/pwessel/UH/RESOURCES/DATA/misc,/Users/pwessel/UH/RESOURCES/DATA/grids,/Users/pwessel/UH/RESOURCES/DATA/img*

*makecpt [DEBUG]: Look for file jet in /Users/pwessel/.gmt/cache*

*makecpt [DEBUG]: Look for file jet in /Users/pwessel/.gmt/server*

*makecpt [DEBUG]: GMT: 0. Will try to find subdir=cpt stem = matlab/jet
suffix=.cpt*

*makecpt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir*

*makecpt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR
/Users/pwessel/.gmt*

*makecpt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir
/Users/pwessel/.gmt/cpt*

*makecpt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share/cpt*

*makecpt [DEBUG]: Given full path to file
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share/cpt/matlab/jet.cpt*

*makecpt [DEBUG]: Found readable file
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share/cpt/matlab/jet.cpt*

*makecpt [DEBUG]: Object ID 0 : Registered CPT File
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share/cpt/matlab/jet.cpt
as an Input resource with geometry Volume [n_objects = 1]*

*makecpt [DEBUG]: gmtapi_begin_io: Input resource access is now enabled
[container]*

*makecpt [DEBUG]: gmtapi_import_palette: Passed ID = 0 and mode = 0*

*makecpt [INFORMATION]: Reading CPT from File
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share/cpt/matlab/jet.cpt*

*makecpt [DEBUG]: Reading CPT from
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share/cpt/matlab/jet.cpt*

*makecpt [DEBUG]: GMT_End_IO: Input resource access is now disabled*

*makecpt [DEBUG]: Set_Object for family: 3*

*==> 1 API Objects at end of GMT_Read_Data*

*--------------------------------------------------------*

*K.. ID RESOURCE.... FAMILY.... ACTUAL.... DIR... S O M L*

*--------------------------------------------------------*

** 0  0    14de057f0 CPT        CPT        Input  2 Y N 1*

*--------------------------------------------------------*

*makecpt [INFORMATION]: CPT is continuous*

*makecpt [DEBUG]: Object ID 1 : Registered CPT Memory Reference 14de05950
as an Input resource with geometry Volume [n_objects = 2]*

*makecpt [DEBUG]: Successfully duplicated a CPT*

*==> 2 API Objects at end of GMT_Duplicate_Data*

*--------------------------------------------------------*

*K.. ID RESOURCE.... FAMILY.... ACTUAL.... DIR... S O M L*

*--------------------------------------------------------*

** 0  0    14de057f0 CPT        CPT        Input  2 Y N 1*

** 1  1    14de05950 CPT        CPT        Input  0 Y N 1*

*--------------------------------------------------------*

*makecpt [DEBUG]: gmt_stretch_cpt: Passed z_low == z_high but CPT has no
explicit range.  No changes made*

*makecpt [DEBUG]: Object ID 2 : Registered CPT Stream 1ddee9170 as an
Output resource with geometry Volume [n_objects = 3]*

*makecpt [DEBUG]: gmtapi_begin_io: Output resource access is now enabled
[container]*

*makecpt [DEBUG]: gmtapi_export_palette: Passed ID = 2 and mode = 0*

*makecpt [INFORMATION]: Write CPT to Stream Standard output stream*

*makecpt [DEBUG]: Writing CPT to <stdout>*

*0 0/0/127 0.125 blue L*

*0.125 blue 0.375 cyan L*

*0.375 cyan 0.625 yellow L*

*0.625 yellow 0.875 red L*

*0.875 red 1 127/0/0 B*

*B black*

*F white*

*N 128*

*makecpt [DEBUG]: GMT_End_IO: Output resource access is now disabled*

*makecpt [DEBUG]: Set_Object for family: 3*

*==> 3 API Objects at end of GMT_Write_Data*

*--------------------------------------------------------*

*K.. ID RESOURCE.... FAMILY.... ACTUAL.... DIR... S O M L*

*--------------------------------------------------------*

** 0  0    14de057f0 CPT        CPT        Input  2 Y N 1*

** 1  1    14de05950 CPT        CPT        Input  0 Y N 1*

** 2  2            0 CPT        CPT        Output 2 Y N 1*

*--------------------------------------------------------*

*==> 3 API Objects at end of GMTAPI_Garbage_Collection entry*

*--------------------------------------------------------*

*K.. ID RESOURCE.... FAMILY.... ACTUAL.... DIR... S O M L*

*--------------------------------------------------------*

** 0  0    14de057f0 CPT        CPT        Input  2 Y N 1*

** 1  1    14de05950 CPT        CPT        Input  0 Y N 1*

** 2  2            0 CPT        CPT        Output 2 Y N 1*

*--------------------------------------------------------*

*makecpt [DEBUG]: gmtlib_garbage_collection: Destroying object: C=0 A=0
ID=0 W=Input F=CPT M=File S=Used P=14de057f0
N=/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/share/cpt/matlab/jet.cpt*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt [DEBUG]: gmtlib_garbage_collection: Destroying object: C=0 A=0
ID=1 W=Input F=CPT M=Memory Reference S=Unused P=14de05950 N=(null)*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt (gmt_support.c:1385(gmtsupport_free_range)): FYI: gmt_M_free given
a NULL pointer - ignored*

*makecpt [DEBUG]: GMTAPI_Garbage_Collection freed 2 memory objects*

*makecpt [DEBUG]: gmtlib_unregister_io: Unregistering object no 0
[n_objects = 2]*

*makecpt [DEBUG]: gmtlib_unregister_io: Unregistering object no 1
[n_objects = 1]*

*makecpt [DEBUG]: gmtlib_unregister_io: Unregistering object no 2
[n_objects = 0]*

*==> 0 API Objects at end of GMTAPI_Garbage_Collection exit*

*gmt [DEBUG]: Entering GMT_Destroy_Session*

*gmt [DEBUG]: Max total memory allocated was 31.539 kb [32296 bytes]*

*gmt [DEBUG]: Single largest allocation was 15.500 kb [15872 bytes]*

*gmt [DEBUG]: Items allocated: 29 reallocated: 10 freed: 29*

*(base) ***@***.***:~-> *


Paul Wessel
Professor Emeritus, Department of Earth Sciences
(808) 956-4778 | ***@***.***
http://www.soest.hawaii.edu/earthsciences

On 23 August 2023 at 19:40:00, Joaquim ***@***.***) wrote:

gmt makecpt -Cjet -Vd

**Comment by boriskaus** [comment]
apologies that this took so long. The latest version of GMT (1.6.0) gives the same mistake. If I run the command you suggested:
```Julia
Julia> using GMT_jll
Julia> julia> run(`$(GMT_jll.gmt()) makecpt -Cjet -Vd`)
gmt [DEBUG]: GMT_Create_Session: Terminal width = 151
gmt [DEBUG]: Obtained the ppid from parent: 40338
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = /workspace/destdir/share
gmt [DEBUG]: GMT->session.HOMEDIR = /Users/kausb
gmt [DEBUG]: GMT->session.USERDIR = /Users/kausb/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = /Users/kausb/.gmt/cache [created]
gmt [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /Users/kausb/.gmt
gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /Users/kausb/.gmt/postscriptlight
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /workspace/destdir/share/postscriptlight
gmt [DEBUG]: GMT: 5. gmt_getsharepath trying SHAREDIR /workspace/destdir/share
gmt [DEBUG]: GMT: 6. gmt_getsharepath failed
gmt [DEBUG]: Map distance calculation will be Cartesian
gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
gmt [DEBUG]: Enter: New_PSL_Ctrl
gmt [DEBUG]: Exit:  New_PSL_Ctrl
gmt [DEBUG]: Enter: gmt_manage_workflow
gmt [DEBUG]: Exit : gmt_manage_workflow
gmt [DEBUG]: Enter: PSL_beginsession
gmt [DEBUG]: Exit : PSL_beginsession
gmt [DEBUG]: Enter: PSL_setdefaults
gmt [DEBUG]: Exit : PSL_setdefaults
gmt [DEBUG]: Enter: gmtlib_io_init
gmt [DEBUG]: Exit : gmtlib_io_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_reload_settings
gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty
gmt [DEBUG]: Look for file /Users/kausb/gmt.conf
gmt [DEBUG]: Look for file /Users/kausb/.gmt/gmt.conf
gmt [DEBUG]: Look for file /Users/kausb/.gmt/server/gmt.conf
gmt [DEBUG]: Look for file /Users/kausb/.gmt/cache/gmt.conf
gmt [DEBUG]: Could not find file gmt.conf
gmt [DEBUG]: Exit:  gmt_reload_settings
gmt [DEBUG]: Enter: gmtlib_plot_C_format
gmt [DEBUG]: Exit:  gmtlib_plot_C_format
gmt [DEBUG]: Enter: gmtinit_get_history
gmt [DEBUG]: Initialize FFTW with 12 threads.
gmt [DEBUG]: GMT_Create_Session initialized GMT structure
gmt [DEBUG]: Loading core GMT shared library: libgmt.dylib
gmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.dylib
gmt [DEBUG]: Loading GMT plugins from: /Users/kausb/.julia/artifacts/33aa99a8b4d8376434e6ace566e0c2e77183f69f/lib/gmt/plugins
gmt [DEBUG]: Shared Library # 1 (supplements). Path = /Users/kausb/.julia/artifacts/33aa99a8b4d8376434e6ace566e0c2e77183f69f/lib/gmt/plugins/supplements.so
gmt [DEBUG]: Revised options: -Cjet -Vd
makecpt [INFORMATION]: Prepare CPT via the master file jet
makecpt [DEBUG]: Look for file jet in /Users/kausb/.gmt
makecpt [DEBUG]: Look for file jet in /Users/kausb/.gmt/cache
makecpt [DEBUG]: Look for file jet in /Users/kausb/.gmt/server
makecpt [DEBUG]: GMT: 0. Will try to find subdir=cpt stem = matlab/jet suffix=.cpt
makecpt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
makecpt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /Users/kausb/.gmt
makecpt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /Users/kausb/.gmt/cpt
makecpt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /workspace/destdir/share/cpt
makecpt [DEBUG]: GMT: 5. gmt_getsharepath trying SHAREDIR /workspace/destdir/share
makecpt [DEBUG]: GMT: 6. gmt_getsharepath failed
makecpt [ERROR]: File /workspace/destdir/share/matlab/jet.cpt was not found
makecpt [ERROR]: Cannot find file /workspace/destdir/share/matlab/jet.cpt
makecpt [ERROR]: File /workspace/destdir/share/matlab/jet.cpt not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
gmt [DEBUG]: Entering GMT_Destroy_Session
ERROR: failed process: Process(setenv(`/Users/kausb/.julia/artifacts/33aa99a8b4d8376434e6ace566e0c2e77183f69f/bin/gmt makecpt -Cjet -Vd`,["XPC_FLAGS=0x0", "COMMAND_MODE=unix2003", "PATH=/Users/kausb/.julia/artifacts/595fba5dbc8bcce7dfc8c029dabcc7c184663ba8/bin:/Users/kausb/.julia/artifacts/63cdaaa4262d5b5b5a880fec012bd9304d6f9a8b/bin:/Users/kausb/.julia/artifacts/8f4f52ca8727c7c18d3a6ff9063aaaed769284f9/bin:/Users/kausb/.julia/artifacts/9472204d25ab69d52d571b650fdc9d562455ca4a/bin:/Users/kausb/.julia/artifacts/9a9f59eab237f7454fee1d6ab112a254032540b7/bin:/Users/kausb/.julia/artifacts/dfa09fc5bd33a68e75b575d8d6565a89814949c2/bin:/Users/kausb/.julia/artifacts/689b6368f94a3d130dce98f67b83f245bebdcbe0/bin:/Users/kausb/.julia/artifacts/825c20e9fb9976a6dc62e1a442018fed80992c1b/bin:/Users/kausb/.julia/artifacts/3e6cbbf76c070bcec6c7db17999b509ac4b46c0d/bin:/Users/kausb/.julia/artifacts/4ec62d729213a748d2300dd0832ebe8ed2292093/bin:/Users/kausb/.julia/artifacts/9cd88b624c5c9ad34fec9c61621c56d465a8c717/bin:/Users/kausb/.julia/artifacts/71f504ed3b6f5f902e1e5f6495be9c3ecdb38986/bin:/Users/kausb/.julia/artifacts/6db94dab8e98dab5bc4428a316ba3f44540bdef2/bin:/Users/kausb/.julia/artifacts/4a1a8201c8ca970558b4321430d5aae3fca6833d/bin:/Users/kausb/.julia/artifacts/df3881e810714d6a09467fe85a6fde79385fe702/bin:/Users/kausb/.julia/artifacts/e6b9fb44029423f5cd69e0cbbff25abcc4b32a8f/bin:/Users/kausb/.julia/artifacts/413111420faa4e2aeaa383c075eaa213402d939c/bin:/Users/kausb/.julia/artifacts/c325a23bc1f6521474cef5f634f18c8ab311bb02/bin:/Users/kausb/.julia/artifacts/0db9c3f6cf936a0da49e2ba954ba3e10bed6ad72/bin:/Users/kausb/.julia/artifacts/1a7e22e66b523d9cb884cf85c3ec065b5fb3e5c3/bin:/Users/kausb/.julia/artifacts/bf37190b92ac2fc3dd5e7073ff7ec7bbfd10343f/bin:/Users/kausb/.julia/artifacts/0d9e7c35bc21411c7d9c194f790e30a95a4a5795/bin:/Users/kausb/.julia/artifacts/33aa99a8b4d8376434e6ace566e0c2e77183f69f/bin:/opt/petsc/petsc-3.18.6-opt/bin/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/opt/python/libexec/bin:/Users/kausb/.julia/bin", "PWD=/Users/kausb/.julia/dev/GMT", "DISPLAY=/private/tmp/com.apple.launchd.GbKLQmXOQy/org.xquartz:0", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=vscode", "HOMEBREW_PREFIX=/opt/homebrew", "VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)", "SHELL=/bin/bash"  …  "_=/usr/local/bin/julia", "HOMEBREW_REPOSITORY=/opt/homebrew", "OPENBLAS_DEFAULT_NUM_THREADS=1", "USER=kausb", "BASH_CONF=bash_profile", "TERM=xterm-256color", "HOME=/Users/kausb", "TERM_PROGRAM_VERSION=1.82.3", "OPENBLAS_MAIN_FREE=1", "COLORTERM=truecolor"]), ProcessExited(16)) [16]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:565 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:480
 [3] run(::Cmd)
   @ Base ./process.jl:477
 [4] top-level scope
   @ REPL[23]:1
```

**Comment by joa-quim** [comment]
The problem starts in here:

```
gmt [DEBUG]: GMT->session.SHAREDIR = /workspace/destdir/share
```

and I have no idea on why that happens for you (and it didn't, or it does not in other computers, because you already had working versions).

What it should have set is (it does for me on Linux)

```
GMT->session.SHAREDIR = /Users/kausb/.julia/artifacts/33aa99a8b4d8376434e6ace566e0c2e77183f69f/share
```

As I mentioned earlier, there in an ENV variable, called `GMT6_SHAREDIR` that may be used to set the share directory. I'm imagining that if you set it, on the Julia side, to point to the above then things will work. But this is not a satisfactory solution. We need to find out the _why_.

**Comment by boriskaus** [comment]
yes, I can confirm that if I set the `GMT6_SHAREDIR` to be `/Users/kausb/.julia/artifacts/33aa99a8b4d8376434e6ace566e0c2e77183f69f/share/` it works fine and all tests are ok. The weird thing is that I did not set that to `/workspace/destdir/share` (it is also not present as an environmental variable) so I am a bit puzzled why it picks this up.

**Comment by joa-quim** [comment]
That ``/workspace/destdir/`` smells to something it inherited from Artifacts build dir names. But why is only (that I know of) happening in your machine is the mystery. I'll try to sneak in the C code to try to see all that is searched when picking the share dir (we have docs about there somewhere in the GMT documentation).

**Comment by boriskaus** [comment]
Indeed puzzling:
```Julia
julia> run(`$(GMT_jll.gmt()) --show-sharedir`);
/workspace/destdir/share
```

**Comment by boriskaus** [comment]
In: `/Users/kausb/.julia/artifacts/33aa99a8b4d8376434e6ace566e0c2e77183f69f/bin/gmt-config` we have:
```
GMT_EXEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Use the executable dir to figure out the lib and include dirs
GMT_TOP=$(dirname $GMT_EXEDIR)
CONFIG_INCLUDEDIR="$GMT_TOP/include/gmt"
# Check if the configure include directory exist.  If so then we craft
# the cflags and lib settings off its parent, else stick with config.
if [ -d $CONFIG_INCLUDEDIR ]; then
  CONFIG_CFLAGS="-I$CONFIG_INCLUDEDIR"
  CONFIG_LIBDIR="$GMT_TOP/lib"
else
  CONFIG_CFLAGS="-I/workspace/destdir/include/gmt"
  CONFIG_INCLUDEDIR="/workspace/destdir/include/gmt"
  CONFIG_LIBDIR="/workspace/destdir/lib"
fi
```

**Comment by joa-quim** [comment]
> Could it be that this is inherited from that?

It has to come from there but note that the CIs tests are run in Linux and Mac and this problem never shows there. It doesn't show either in my WSL environment.

**Comment by boriskaus** [comment]
> > Could it be that this is inherited from that?
> 
> It has to come from there but note that the CIs tests are run in Linux and Mac and this problem never shows there. It doesn't show either in my WSL environment.

yes that is indeed weird. I did have a `/workspace/destdir` directory on my system (for testing other BB packages). Yet, renaming that did not change the situation.  

A hack would be to check in `GMT.jl` if an environmental variable with the name `GMT6_SHAREDIR` exists. If not *and* we are using `GMT_jll`, set it explicitly to the correct one. 
If this indeed is a common problem it should have been spotted by the CI

**Comment by joa-quim** [comment]
It has to be this. See this line 
https://github.com/GenericMappingTools/gmt/blob/master/src/gmt_init.c#L3566
The ``GMT_SHARE_DIR`` is a variable that is set at compile time and you will find it in the ``config.h`` file in
```
/Users/kausb/.julia/artifacts/33aa99a8b4d8376434e6ace566e0c2e77183f69f/include/gmt
```
Mine, on Linux, says
```
/* path to shared files */
#define GMT_SHARE_DIR "/workspace/destdir/share"
```
But because that `dir` does not exist in my installation the ``gmtinit_set_env()`` keeps searching until it finds one. In your case it stops because it finds one ``/workspace/destdir/share``.

Like I started. It has to be this.

**Comment by boriskaus** [comment]
Yes that makes sense. It could be that it doesn’t work in my system after I renamed `/workspace/..` because it was precompiled. Do you know how to force recompilation of GMT?

**Comment by joa-quim** [comment]
I used to have a function for that but it no longer. Probably the easiest is to delete the shared lib in “compileds”.  Not at the computer right now.

**Comment by boriskaus** [comment]
I can confirm that it works fine after renaming `/workspace/..`.

This thus implies that `GMT.jl` will not work when users have a directory called `/workspace/..` on their system. It's probably a good idea to catch that case in the Julia package but I leave that up to you.

**Comment by joa-quim** [comment]
Please remind me. You had one such directory (`/workspace/destdir/share`) because you build with `PackageCompiler` locally and it creates that directory name?

**Comment by boriskaus** [comment]
no, I had created that directory on my machine to debug another `binarybuilder` package.

**Comment by boriskaus** [comment]
the issue is solved by ensuring that you don't have a directory called `/workspace/destdir` on your machine.
