### ISSUE TITLE
Error compiling GMT

### ISSUE THREAD

**Issue by christinegz** [GenericMappingTools/GMT.jl#13]
With julia v"0.6.0", GMT.jl v"0.3.0" and GMT 5.4.2 on Windows 8, I receive this error message when using a gmt command in julia.

error compiling gmt: could not load library "gmt_w64"

Do you have an idea how to fix this?

**Comment by joa-quim** [comment]
Hmm, what was the command that you run that gave “error compiling gmt” error?

 

could not load library "gmt_w64" smells like a path problem finding the gmt_w64.dll file.

**Comment by christinegz** [comment]
I tried commands from examples, like:

>gmt("pscoast -Rg -JA280/30/3.5i -Bg -Dc -A1000 -Gnavy -P > GMT_lambert_az_hemi.ps")
ERROR: error compiling gmt: could not load library "gmt_w64"

 or 

>plot(collect(1:10),rand(10), lw=1, lc="blue", fmt="png", marker="square",
            markeredgecolor=0, size=0.2, markerfacecolor="red", title="Hello World",
            x_label="Spoons", y_label="Forks", show=true)
ERROR: error compiling #xy#84: error compiling monolitic: error compiling gmt: could not load library "gmt_w64"
The specified module could not be found

Where can I set the path of the gmt_w64.dll file?

**Comment by joa-quim** [comment]
Is your GMT installation running fine (other from this Julia issue)? Because ``gmt_w64.dll`` is in the  GMT's ``bin`` dir, which is supposed to be in system's path, and there is nothing you should do more.
If you want to set the path to ``gmt_w64.dll`` explicitly look at the first line of [libgmt](https://github.com/GenericMappingTools/GMT.jl/blob/v0.3.0/src/libgmt.jl#L1)

**Comment by christinegz** [comment]
The GMT installation runs fine otherwise. By setting the gmt-path explicitly in libgmt.jl it now works. Thanks for your help!

**Comment by joa-quim** [comment]
I don't understand how it can be in the path and not being found, but if works for you, so be it. 
Mind you when you update GMT.jl in future. You may need to do this again.
