### ISSUE TITLE
Crash when "gray" CPT is used

### ISSUE THREAD

**Issue by ZMAlt** [GenericMappingTools/GMT.jl#1472]
Hi, @joa-quim

I found a weird crash when "gray" CPT is used.

```julia
using GMT
grd = grdcut("@earth_relief_01d", region = (110, 120, 10, 20))
cpt = grd2cpt(grd, C = "gray")  # same situation for makecpt
grdimage(grd, C = cpt, savefig = "test.pdf")
```
If "gray" is replaced with other cpt, there is no crash.

**Comment by joa-quim** [comment]
Confirm it too. Thanks.

**Comment by joa-quim** [comment]
This is due to a [bug in GMT](https://github.com/GenericMappingTools/gmt/pull/8522) that returns a conflicting info for the gray.cpt master CPT. Fixed in master by testing if the colors are gray or not.

**Comment by ZMAlt** [comment]
Great.
I have tested it using the master branch.  It works now.
Thank you.
