### ISSUE TITLE
Not finding libgdal-35.dll on windows

### ISSUE THREAD

**Issue by boriskaus** [GenericMappingTools/GMT.jl#1479]
I have an issue with my CI which fails on windows due to the following GMT.jl precompilation [error](https://github.com/JuliaGeodynamics/GeophysicalModelGenerator.jl/actions/runs/9750547514/job/26910198517?pr=131#step:6:992):
```
Failed to precompile GMT [5752ebe1-31b9-557e-87aa-f909b540aa54] to "C:\\Users\\runneradmin\\.julia\\compiled\\v1.12\\GMT\\jl_78A2.tmp".
ERROR: LoadError: InitError: could not load library "C:\Users\runneradmin\.julia\artifacts\9db36ce542776801f81c6432d08864ea4abfc279\bin\libgdal-35.dll"
The specified module could not be found. 
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl .\libdl.jl:120
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl .\libdl.jl:119
  [3] top-level scope
    @ C:\Users\runneradmin\.julia\packages\GDAL_jll\EQFRa\src\wrappers\x86_64-w64-mingw32-cxx11.jl:78
  [4] macro expansion

```
Works fine on Linux/Mac.
Does it look familiar?

**Comment by joa-quim** [comment]
Yes. GDAL is broken on Windows and oddly they are taking long to revert the breaking change.
Solvable by reinstalling older version. _e.g._ `add GDAL_jll@301.900`
See also https://discourse.julialang.org/t/gmt-fails-to-precompile-in-julia-1-10-4/116391/6

**Comment by boriskaus** [comment]
thanks - that indeed solved it!

**Comment by boriskaus** [comment]
In fact, why don't you limit the version of `GDAL_jll` within the `GMT.jl` package? That would give a more positive experience for `GMT.jl` users;  you can release that limitation, once a new version of `GDAL_jll` is released that fixes the issue.
What you would need to do is add the following `[compat]` in [Project.toml](https://github.com/GenericMappingTools/GMT.jl/blob/2fb480677cba0becd46e79be31c570d0681940ff/Project.toml#L29) (or something like that; I just took a random lower bound):
```julia
[compat]
GDAL_jll = "300.900.0 - 301.900.0"
```

**Comment by joa-quim** [comment]
Thanks, I did that in v1.15.2.

Can't understand how they live it in a broken state for almost a week (and counting).
