### ISSUE TITLE
Cannot parse option -l

### ISSUE THREAD

**Issue by ZMAlt** [GenericMappingTools/GMT.jl#1486]
```julia-repl
julia> plot([2 2], J = "X3c", S = "c2p", R = "1/5/1/5", B = "af", l = "pos", savefig = "test.pdf")
Warning: the following options were not consumed in psxy => [:l]

julia> plot([2 2], J = "X3c", S = "c2p", R = "1/5/1/5", B = "af", label = "pos", savefig = "test.pdf")

julia> 
```

**Comment by joa-quim** [comment]
That is because ``-l`` is an option available only in GMT's modern mode, whilest `label` is the attempt to reproduce `l` in classic mode. That is, they are different options trying to achieve the same result.

**Comment by ZMAlt** [comment]
```julia
gmtbegin("test2.pdf")
plot([2 2], J = "X3c", S = "c2p", R = "1/5/1/5", B = "af", l = "pos")
gmtend()
```
The code above does produce a legend. However, the warning remains. 
I think the warning should be removed, or make `l` and `label` acceptable in any mode.

**Comment by joa-quim** [comment]
Checking the code, `l` or `label` were intended to work in both modes but it was not fully working. Hopefully it is now in master.

**Comment by ZMAlt** [comment]
At the moment, It‘s still not fully working in master as follows.

----

There is a legend with either `l` or `label` in classic mode. The warning remains for `l`.

```julia-repl
julia> plot([2 2], J = "X3c", S = "c2p", R = "1/5/1/5", B = "af", l = "pos", savefig = "test.png")
Warning: the following options were not consumed in psxy => [:l]

julia> plot([2 2], J = "X3c", S = "c2p", R = "1/5/1/5", B = "af", label = "pos", savefig = "test.png")

julia>
```
![test](https://github.com/user-attachments/assets/cc407479-0275-466b-a76f-8ad9811562ae)

----

In modern mode, there is no legend with `label`
```julia-repl
julia> gmtbegin("test.png")

julia> plot([2 2], J = "X3c", S = "c2p", R = "1/5/1/5", B = "af", l = "pos")

julia> gmtend()

julia> gmtbegin("test.png")

julia> plot([2 2], J = "X3c", S = "c2p", R = "1/5/1/5", B = "af", label = "pos")
Warning: the following options were not consumed in plot => [:label]

julia> gmtend()

julia>
```
`l`
![test](https://github.com/user-attachments/assets/41ba4b4f-b962-453d-b03d-7ad1e31f8dc2)

`label`
![test](https://github.com/user-attachments/assets/1cc6589a-3166-460e-b2ed-54bc977ec3dc)

**Comment by joa-quim** [comment]
Will look again when finished another issue I'm working in.

**Comment by joa-quim** [comment]
I have fixed some of those cases, but not the last. `l` is an alias to `legend`, not to `label`.

**Comment by ZMAlt** [comment]
I see. I think it works well. Time to close this. Thank you.
