### ISSUE TITLE
wmsread fails on  wms=wmsinfo("http://ows.mundialis.de/services/service")

### ISSUE THREAD

**Issue by robot144** [GenericMappingTools/GMT.jl#1500]
Hi,

When trying the following code:
`wms=wmsinfo("http://ows.mundialis.de/services/service")
img = wmsread(wms, layer="OSM-WMS", region=(0.0,2.0,50.0,52.0), size=(800,800));
imshow(img)

`
The image is mostly blue. After some searching this seems to result from wmsinfo setting the wms.layer[i].srs to the wrong values. When I overrule the srs by "EPSG:4326" then it does work. Not that the struct for a layer is not mutable, so I used:
```
#  struct GMT.WMSlayer
#  name          :: String
#  title         :: String
#  srs           :: String
#  crs           :: String
#  bbox          :: NTuple{4, Float64}
#  imgformat     :: String
#  tilesize      :: Int64
#  overviewcount :: Int64
#  resolution    :: Float64
#  tiled         :: Bool
#  transparent   :: Bool
l1_new=GMT.WMSlayer(l1.name,l1.title,"EPSG:4326",l1.crs,l1.bbox,l1.imgformat,l1.tilesize,l1.overviewcount,l1.resolution,l1.tiled,l1.transparent)
wms.layer[1]=l1_new
```
I guess that the parsing of the variable f fails in function wmsinfo in file webmapserver.jl around line 51 fails.
It would be nice if this could be fixed, but I don't dare to try this myself, since I am new to GMT.jl

Many thanks for the nice package,
Martin

**Comment by joa-quim** [comment]
Hi Martin, thanks for looking for the error. I’m on mobile so can’t check it right now. 
But don’t be afraid to screw anything in the code. You can’t. If you fork the project and install it locally you can do all experiments you want and if you manage to fix it than you can submit a PR (Pull Request).
