### ISSUE TITLE
GMT build error in Julia 1.11 and GMT@v1.20

### ISSUE THREAD

**Issue by CyprienBosserelle** [GenericMappingTools/GMT.jl#1574]
Hi,
I've noticed a build error when installing GMT.jl (`] add GMT@v1.20.0`) on a new computer and current stable Julia (v1.11 but also occur with current LTS)  .

I appears because of a call to `replace` with 3 arguments in line 68 of build.jl (`Sys.iswindows() && (userdir = replace(userdir, "/", "\\"))`) whereas it should be `Sys.iswindows() && (userdir = replace(userdir, "/" => "\\"))` for newer version of Julia (>=1.7 ?)

Funny thing is build.jl seem to only be called on fresh install. If I install @v1.15 and then upgrade to @v1.20 it just seem to work.

I'm happy with this workaround but I thought you may want to fix this.
Cheers
Cyp 

### Error message:
```
ERROR: Error building `GMT`:
ERROR: LoadError: MethodError: no method matching replace(::String, ::String, ::String)
The function `replace` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  replace(::AbstractString, !Matched::Pair...; count)
   @ Base strings\util.jl:936
  replace(!Matched::IO, ::AbstractString, !Matched::Pair...; count)
   @ Base strings\util.jl:933
  replace(!Matched::Union{Function, Type}, ::Any; count)
   @ Base set.jl:868
  ...

Stacktrace:
 [1] get_de_libnames()
   @ Main C:\Users\XXX\.julia\packages\GMT\yRgLc\deps\build.jl:63
 [2] top-level scope
   @ C:\Users\XXX\.julia\packages\GMT\yRgLc\deps\build.jl:78
 [3] include(fname::String)
   @ Main .\sysimg.jl:38
 [4] top-level scope
   @ none:5
in expression starting at C:\Users\XXX\.julia\packages\GMT\yRgLc\deps\build.jl:71
```

**Comment by joa-quim** [comment]
Thanks for the catch. But quite strange that no one, me included that build and use on Windows, have crossed this before.
So, you have GMT installed outside of Julia, right? But even here I had the recall that the JLL solution (that is, an automatic install of the GMT-built-with-BinaryBuilder) was taking place.

Any way, I'll submit a PR to fix this in master may tonight still.

**Comment by CyprienBosserelle** [comment]
Yes I installed GMT 6.5.0 outside of julia before event installing Julia. (Happy to report that GMT is first software I install on a new machine... ). But it is very strange indeed, it took a few trial to make sure I could replicate it in my environment. Being on a new PC i wasn't afraid of breaking everything so I uninstalled Julia, deleted my `.julia` folder (could not replicate the error otherwise) and made a fresh install of Julia and the 
```] add GMT@v1.20.0```

The error came at compile time.

**Comment by joa-quim** [comment]
What do you get when typing this on REPL? 
```
GMTver
```

The point is that GMT6.5.0 starts to be a bit outdated. I made a few changes in it and now rely on them in GMT.jl
This version is slightly better, but even it needs to be updated
https://fct-gmt.ualg.pt/mirone/gmt-6.6.0_dev_2024.07.03-win64.exe

The JLL version is more updated (but that's not what I use. I use the MSVC GMT build).

And, I see you are using Julia 1.11. Well, I prefer 1.10. 1.11 produces larger binaries, is slower to compile and to load.

**Comment by joa-quim** [comment]
So that confirms what I had in mind. Somewhere in the building procedure Julia stop taking the `build.jl` _seriously_ (though it still may error like you found) and always installs the GMT JLL build. Though I prefer my own MSVC build, this is not actually bad as it is much simpler for me to have the users always using an updated GMT version. And because of this I have not really invested in finding out why things are the way they are.
In case you would still want to use the system installed GMT, this is what I have in the `deps.jl` that should be generated by `build.jl`
```
_libgmt  = "c:/programs/GMTDIR/gmt_w64.dll"
_libgdal = "c:/programs/GMTDIR\\gdal_w64.dll"
_libproj = "c:/programs/GMTDIR\\proj_w64.dll"
_GMTver = v"6.6.0"
devdate = "2024.07.01"
userdir = "C:\\Users\\j\\.gmt"
have_jll = 0
``` 

> Could explain the strange behaviour in https://github.com/GenericMappingTools/GMT.jl/issues/1575?

No, I don't see any possible relation.

**Comment by CyprienBosserelle** [comment]
Yes I like that I can have Julia use the latest GMT without bothering IT crew about updating my installed version.
I wiped (deleted my .julia)and reinstalled Julia (v1.10) and `add GMT` worked without error but you are right it installed v6.6.0 but that's great.
Cheers
Cyp
