### ISSUE TITLE
Add ggplot2-like Features for geom_raster and geom_sf in GMT.jl

### ISSUE THREAD

**Issue by Jigyasu4indp** [GenericMappingTools/GMT.jl#1585]
First of all, thank you very much for developing the GMT package. Could you consider expanding the documentation to comprehensively cover all features, including base maps, raster data visualization over base maps, global overlays, and enhanced data visualization? It would be particularly helpful to include examples of features like color bars, scale bars, facet wrapping, and facet grids.

Additionally, could you please add functionality similar to geom_raster and geom_sf from ggplot2 in R? This would be a tremendous aid in producing high-quality plots for publication and promoting Julia as a tool for geospatial visualization.

**Comment by joa-quim** [comment]
Hi, thank you for the interest.
Although you opened a similar issue in the GMT_doc site I am not sure you actually dived in the documentation there.

> cover all features, including base maps, raster data visualization over base maps, global overlays, and enhanced data visualization? It would be particularly helpful to include examples of features like color bars, scale bars, facet wrapping, and facet grids.

Well that's a lot of things to ask, but aren't most of those covered in the documentation examples. Let's take the color bars example. Aren't those comprehensive enough?

https://www.generic-mapping-tools.org/GMTjl_doc/documentation/modules/colorbar/index.html#colorbar
https://www.generic-mapping-tools.org/GMTjl_doc/examples/CPTs/

> facet wrapping, and facet grids.

Sorry I have no idea of what are these.

Can you point me to examples of things that you can do with those but not with `grdimage`, `grdview`, `triangulate`, `pcolor`, `plot`?

And, have you seen this one?

https://www.generic-mapping-tools.org/GMTjl_doc/tutorials/vector_shp/vector_shp

**Comment by joa-quim** [comment]
Any feedback? Otherwise I'll close this issue.

**Comment by joa-quim** [comment]
Closing due to lack of feedback.

**Comment by Jigyasu4indp** [comment]
Please close this. If any additional information is required, I will request it after reviewing your example.
