### ISSUE TITLE
-D option in makecpt not working

### ISSUE THREAD

**Issue by hydrocoast** [GenericMappingTools/GMT.jl#179]
I'm wondering why **-D** option in makecpt doesn't work under certain condition. 

My environment is as follows:
- Ubuntu 18.04 LTS
- Julia v1.0.0 (or later)
- GMT.jl v0.7.0

The following is one use for makecpt:
```julia
cptfile = "tmp.cpt"
using GMT: GMT

GMT.gmt("makecpt -Cpolar -T-1/1 -D > $cptfile")
```

It works properly and returns
```julia
txt = readlines(cptfile)
println.(txt)
```
```
-1  blue    0   white
0   white   1   red
B   blue
F   red
N   127.5
```

However,  **-D** doesn't work when the following codes run:
```julia
cpt = GMT.makecpt(C=:polar, T="-1/1", D="any string or bool")
```
```julia
cpt = GMT.gmt("makecpt -Cpolar -D -T-1/1")
```
These return
```julia
GMT.gmt("write $cptfile", cpt)
txt = readlines(cptfile)
println.(txt)
```
```diff
 -1  blue    0   white
 0   white   1   red
- B   blue
- F   red
+ B   black
+ F   white
 N   127.5
```

I tried to find out the cause by tracing `GMT.gmt`  at [gmt_main.jl](https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gmt_main.jl) and `GMT.makecpt`  at [makecpt.jl](https://github.com/GenericMappingTools/GMT.jl/blob/master/src/makecpt.jl) but I couldn't.  

Does anyone know how to fix this?

**Comment by joa-quim** [comment]
If you look at the makecpt man page you see that -D can only have one (optional) character ``-D[i|o]``. This means one cannot do (here I use the -Vd to print out the generated gmt command)
```
julia> cpt = GMT.makecpt(C=:polar, T="-1/1", D="any string or bool", Vd=1);
        makecpt  -Cpolar -Dany string or bool -T-1/1
makecpt [ERROR]: Syntax error: No input files expected unless -E or -S are used
```

However, you are right that there is a problem with -D. Actually it seems to not be taken into account at all when using the long options version (or, most likely, its effects were not brought back to the Julia side)
```
cpt = GMT.makecpt(C=:polar, T="-1/1", D=true, Vd=1);
        makecpt  -Cpolar -D -T-1/1

julia> cpt.bfn
3×3 Array{Float64,2}:
 0.0  0.0  0.0
 1.0  1.0  1.0
 0.5  0.5  0.5
```

**Comment by joa-quim** [comment]
I'm afraid this issue may report back to the GMT lib itself. I find the same behavior in the Matlab wrapper as well.

**Comment by hydrocoast** [comment]
Thank you.
I thought there might be problem with the GMT lib itself since this involves `ccall` at `GMT_Call_Module` but it's not so clear to me.
