### ISSUE TITLE
variable name error in documentation: `scaleat_lat` could be `scale_at_lat`

### ISSUE THREAD

**Issue by kura-okubo** [GenericMappingTools/GMT.jl#272]
Dear GMT.jl contributors,

I found an error of variable name in the documentation of [coast](https://www.generic-mapping-tools.org/GMT.jl/latest/coast/).

## Enviroment
macOS Mojave 10.14.5
gmt 5.4.5

## Issue
In the explanation of `-L or map_scale`:

>– mapscale=([map=true, inside=true, norm=true, paper=true,] anchor=refpoint, scaleat_lat=lat, length=len [,align=side, justify=code, fancy=true, label=lab, offset=(dx,dy), units=unit, vertical=true])

**scaleat_lat** could be **scale_at_lat**. This causes error when plotting map scale on the figure.

## To reproduce that error
```
using GMT

region = "-5/42/10/52.5r"
proj = (name=:Cassini, center=[2.2 48.5])

# This works
map_scale=(map=true, anchor=[5, 44.5], scale_at_lat=45,  length=200, fancy=true, label="[km]")
p = coast(region=region, proj=proj, map_scale=map_scale, land=:gray, DCW=((country="FR", pen=(0.5,:black))), show=true)

# This causes error
map_scale=(map=true, anchor=[5, 44.5], scaleat_lat=45,  length=200, fancy=true, label="[km]")
p = coast(region=region, proj=proj, map_scale=map_scale, land=:gray, DCW=((country="FR", pen=(0.5,:black))),  show=true)

# error message
> pscoast: Syntax error -L option:  Scale origin modifier +c[<lon>/]/<lat> is required

```

## Expected result
Map scale is shown in the figure:
![GMTjl_tmp](https://user-images.githubusercontent.com/20231193/59520563-411b6b80-8e98-11e9-871b-c01c4ea9c7dd.png)

## Current result
It does not work with incorrect variable name.

It would be nice if you could modify the documentation.

Best regards,

**Comment by joa-quim** [comment]
@kura-okubo  Thank you for this info but I'm puzzled because the the markdown source code correctly says ``scale_at_lat``. See https://github.com/GenericMappingTools/GMT.jl/blob/master/docs/src/coast.md

**Comment by joa-quim** [comment]
I believe this now solved (very likely a Julia or Documenter bug)

**Comment by kura-okubo** [comment]
Thank you for fixing that!
