### ISSUE TITLE
some Longitude regions will cause strange lines

### ISSUE THREAD

**Issue by htyeim** [GenericMappingTools/GMT.jl#398]
If I want to plot a region with longitude from 170 to 140 (which means 170-180 0-140, all without 140-170).
I can't give the region like this (170,140,-90,90), as GMT.jl/gmt will rise a error `basemap [ERROR]: Option -R parsing failure. `. But I found that the region could be (170-360,140,-90,90) or (170,140+360,-90,90). In most case it work fine, but for large regions like (170-360,155,-90,90) there will be some strange lines...

The code that can produce the strange figures:
```
using GMT
function test(rlon=[170,128])
    gmtbegin()
    gmtfig(string("test_R_", rlon[1], "_", rlon[2]), fmt="png")
    if rlon[1] > rlon[2]
        rlon[1] -= 360
    end
    baseregion = (rlon[1], rlon[2], -90, 90)
    lon = (baseregion[1] + baseregion[2]) / 2.0
    proj = (name = :Robinson,
            # center = [mean(baseregion[1:2]) mean(baseregion[3:4])],
            center = lon,)
    basemap(region=baseregion, proj=proj, frame=(axes = :WSen,),
                figsize=12, )
    topo = makecpt("-H", color=:geo, range=(-8800, 8800,), continuous=true);

    grdimage!("@earth_relief_20m.grd", region=baseregion,
                nan_alpha=true,
                color=topo,
                colorbar=true)
    coast(region=baseregion, 
            borders=(type = :a, pen = (0.06, :black, "--")),
            shore=(type = 1, pen = (0.6, :black,)), 
            # Vd=1,
            )
    gmtend()
end

for lon_right = 5:10:170
    test([170,lon_right]) 
end
```

(170,5,-90,90)
![test_R_170_5](https://user-images.githubusercontent.com/17849322/87635855-51c0a400-c772-11ea-9efc-a7914e06077f.png)

(170,145,-90,90)
![test_R_170_145](https://user-images.githubusercontent.com/17849322/87635837-4bcac300-c772-11ea-955c-b4ca45e36edd.png)

(170,155,-90,90)
![test_R_170_155](https://user-images.githubusercontent.com/17849322/87635866-57b68500-c772-11ea-93e6-b672cb74151d.png)

(170,165,-90,90)
![test_R_170_165](https://user-images.githubusercontent.com/17849322/87635887-5dac6600-c772-11ea-8766-296a00e0f12a.png)

It seems starts from (170,151) the strange lines appear. I don't know if this is related to https://github.com/GenericMappingTools/GMT.jl/issues/357

**Comment by joa-quim** [comment]
It's a GMT bug. We have had bugs of this type since immemorial times. Can be reproduced with
```
coast(proj=(name=:Robinson, center=-18), region=(-190,155,-90,90),  show=1)
```

**Comment by joa-quim** [comment]
However the same command will work if we use a higher coastlines resolution. 
```
coast(proj=(name=:Robinson, center=-18), region=(-190,155,-90,90), resolution=:low, show=1)
```
when resolution is not set the program uses resolution=automatic, which for these limits turn out to be resolution=:crude. However, although this may solve the current case it may very well show up in other limits combination. I will open an issue in GMT.

**Comment by htyeim** [comment]
I remember that when I used matplotlib (with [cartopy](https://scitools.org.uk/cartopy/docs/latest/index.html)) there are also some strange lines, especially when [orthographic](https://scitools.org.uk/cartopy/docs/latest/crs/projections.html#orthographic) projection is used. They are both almost pure python packages but when I try to check the source code it's so hard to read and track variables (maybe I don't have enough knowledge...). Anyway I have changed my main program language to Julia and so far so good.

The main problem I think is related to the geographic longitude range. 180/-180 (0/360) are the same line. When I try to plot large scale maps, I always need to check again and again...

Also I think that it would be great if GMT could accept region range like (90, 60, -90,90) (lon1>lon2) and then plot longitude range from 90 to 180 then from -180 to 60.

**Comment by joa-quim** [comment]
The problem is that when a polygon is cut in, say, the left side and continues in the right side, that polygon has to be split in two and one of the halves needs to modified to plot correctly on the other side. And this is not only restricted to geographical. What has happen is that there are many combinations depending on the projection and some cases continue to fail. Only Paul has the patience (and knowledge) to keep tracing these failures.

Several years ago we have had a discussion about the possibility of letting ``w`` > ``e`` in limits but, and I don't remember why, we decided against. Note that this would make sense only in geographical coordinates.

**Comment by htyeim** [comment]
Thank you.... More complex than I though 😸  I think I can just check the region before I call GMT functions...
