### ISSUE TITLE
Issue with GMT.jl installation for Julia 1.5.0 on Windows 10

### ISSUE THREAD

**Issue by RafaelBGu** [GenericMappingTools/GMT.jl#451]
Summary of GMT.jl installation procedure for Julia 1.5.0 on Windows 10 and of issue faced:
1) Installed latest GMT6.1.1 for Windows (64bits)
2) Installed also latest windows (64 bits) versions of: ghostscript and gsviewer (the latter has discontinued support)
3) In Julia tried both: pkg>add GMT and also pkg>add GMT#master.
4) Added to windows PATH:  "C:\programs\gmt6\bin"
5) Testing with: pkg> test GMT, was successful: "Testing GMT tests passed"

Problem:
- when I try to run any of the Julia GMT examples in Julia 1.5, get error message:  "ERROR: UndefVarError: API not defined"

Thank you for shedding some light on this issue.

**Comment by RafaelBGu** [comment]
I must add that the above "API not defined" error occurs in VS Code's Julia REPL.
I have just realized that if I launch the Julia 1.5.0 console, the GMT examples do work fine.
I guess I should submit this issue to the VS Code Julia extension team?

**Comment by joa-quim** [comment]
Hi @RafaelBGu a problem on Windows for change (they always come from *nix 😄 )

So, 
- GMT installer comes with a ghostscript. No need to install the *official* but no harm either.
- GMT installers adds itself to the path. Except when the path is too long for ``cpack``. 1024 chars, which unfortunately happens too often but not at all our fault.

But to the point and I'm sorry to not have an idea (please post the full stack trace). I do lots (really lots) of trials from VSCode when debugging and never had that problem.

**Comment by RafaelBGu** [comment]
Hi joa-quim, thank you for your support and my apologies for my inexperience on this. Today after restarting, I do not get the "API not defined" error any longer when running GMT via VS Code's Julia extension. And I am very happy now!
