### ISSUE TITLE
Figure size proportions not respected in GMT6.1.1

### ISSUE THREAD

**Issue by rafael-guerra-www** [GenericMappingTools/GMT.jl#452]
The figure proportions are distorted when running @joa-quim 's GMT code from [Julia discourse](https://discourse.julialang.org/t/save-matrix-of-rgb-values-to-image-file-with-huge-pixels/47771/6) in Windows 10 (GMT6.1.1):
```julia
using GMT
im = ones(UInt8,2, 2, 3); im[1,1,1]=255; im[1,2,1]=255; im[1,1,2]=255; im[2,1,2]=255; im[1,1,3]=255; im[2,2,3]=255;
imshow(im,axes=:none, figsize=10, savefig="huge_pix.png")
```
![huge_pix](https://user-images.githubusercontent.com/20739393/95169212-338ba280-07bb-11eb-8ec9-8c68359e43d5.png)

**Comment by joa-quim** [comment]
I think I know the reason for this. GMT itself had some bugs in its ``grdimage`` module regarding the pixel registration used by images. And those bugs have been fixed in the *dev* version, the one I use where the result is correct.

**Comment by joa-quim** [comment]
If you want to try updating your GMT version with this http://fct-gmt.ualg.pt/mirone/gmt-6.2.0_2020.10.19-win64.exe I think the problem will be solved for you too.

**Comment by RafaelBGu** [comment]
Joaquim, thank you for the new GMT version 6.20. The matrix plot now displays perfectly in my Win10 machine:
![huge_pix_Win10_GMT6 2 0](https://user-images.githubusercontent.com/20739393/96465526-bab42e00-1231-11eb-912f-18dd7e6dc77e.png)

**Comment by RafaelBGu** [comment]
Joaquim, I would like to update my post in [Julia discourse](https://discourse.julialang.org/t/save-matrix-of-rgb-values-to-image-file-with-huge-pixels/47771/7?u=rafael_guerra) but the new Windows GMT version does not seem to be publicly available yet? At least not at: https://www.generic-mapping-tools.org/download/

**Comment by joa-quim** [comment]
Well, at the official GMT page we only have the official releases. The one I pointed you out can be seen as a nightly release. On *nix users can relatively easily compile GMT but it's more complicated on Windows, so I make some from time to time. An official 6.2 version is expected in a couple of months.

**Comment by RafaelBGu** [comment]
Ok, understood. Would it be alright to say in Julia discourse that issue observed has been fixed in the nightly release of GMT for Windows which will be part of next official release. The compiled Windows version (GMT 6.2.0) provided by joa-quim does not show the bug (attachment above)?

**Comment by joa-quim** [comment]
Yes, that would be fine thanks. Buts just a small correction, the fix was in the GMT master, which is available if compiling from source. The Windows installer GMT 6.2.0dev is a user commodity.

**Comment by RafaelBGu** [comment]
Thank you, will do.
