### ISSUE TITLE
my own data to GMT

### ISSUE THREAD

**Issue by lazarusA** [GenericMappingTools/GMT.jl#465]
Hello,
I have being playing a little bit with all the examples in the library. They work nicely. Thanks for the effort. However, is there an easy way to transform my own data into the GRID type in order to use it with gmt ?
Suppose I have 3 arrays. 
```
> longitude [1440-element Array{Float64,1}]
> latitude 1D array [720-element Array{Float64,1}]
> temperature 2D array [1440×720 Array{Float64,2}]
```

how do I pass this data to `grdimage` for instance?

**Comment by joa-quim** [comment]
Have a look at ``mat2grid``. *e.g.*
```
? mat2grid
```

**Comment by lazarusA** [comment]
nice! this one works!... you have a lot of good functions, unfortunately one needs to go to the source code to look for them. Thanks.

**Comment by joa-quim** [comment]
Yes, I know. There are lots of work needed in the documentation front. BTW, you may have found also ``mat2img`` and ``mat2ds``.
