### ISSUE TITLE
Leakage in contourf filled contours?

### ISSUE THREAD

**Issue by RafaelBGu** [GenericMappingTools/GMT.jl#470]
There seems to be some leakage in GMT's contourf filled contours, as per code below and attached picture with result.
I have GMT "6.2.0_6f6d002-dirty_2020.10.19" installed in Windows 10 and I am running Julia 1.5.2 using VS Code.

```julia
using GMT
G = GMT.peaks(N=100)
zmin, zmax = floor(minimum(G)), ceil(maximum(G))
colorstep = 0.1; contstep = 1; annotstep = 2;
C = makecpt(T=(zmin,zmax,colorstep), cmap=:geo);
contourf(G, C, cont=contstep, annot=annotstep, conf=(MAP_GRID_PEN_PRIMARY=0.1,),
        frame=(axes=(:left_full, :bot_full),),
        xaxis=(grid=1, annot=1, ticks=:auto, label="X [km]"),
        yaxis=(grid=1, annot=1, ticks=:auto, label="Y [km]") )
colorbar!(pos=(paper=true,anchor=(13,1),size=(10,0.5), vertical=true),
        frame=(annot=1, ticks=1, xlabel="Elevation [m]"), fmt=:png, show=true)
```
![GMTjl_contourf_fill_leaks](https://user-images.githubusercontent.com/20739393/97786481-7f601a80-1bb4-11eb-82b1-1ea5ddc22ff6.png)

**Comment by joa-quim** [comment]
Hmm, don't know what is going on but it's on the pure GMT side. Saving the ``peaks`` grid and
```
makecpt -Cgeo -T-7.0/9.0/0.1 > lixo.cpt
grdview peaks.grd -JX12c/0 -Bpa1fg1 -BWS -Qs -R-3/3/-3/3 -Clixo.cpt -P  > lixo.ps
```
shows the same effect
@PaulWessel

**Comment by PaulWessel** [comment]
Just letting you know I am looking at this.

**Comment by PaulWessel** [comment]
grdview has lots of comments regarding past problems (near line 1660), which is very helpful.  We are making sure _small_ (the noise we add to prevent a contour from going exactly through a node) is not smaller then floating point EPS, but it can be larger.  Here it was 0.000364651 based on 

`small = GMT_CONV4_LIMIT * (Z->header->z_max - Z->header->z_min);`

I wonder why it cannot just (always) be just slightly larger than EPS (e.g., 1.0e-7).  When I set _small_ to that value the problem went away.  So I understand the problem and will work on a solution.

**Comment by joa-quim** [comment]
This now solved in GMT.

**Comment by RafaelBGu** [comment]
Dear Joaquim and Paul, just a word of recognition for your follow and for the very fast fix. Thank you.
