### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by ali-ramadhan** [GenericMappingTools/GMT.jl#534]
Clicking on the latest docs badge sends me to https://www.generic-mapping-tools.org/GMT.jl/latest which produces a 404 not found error.

**Comment by joa-quim** [comment]
Thanks for the warning. I'm not sure what is happening. I'm trying to register a 0.30 version but some autobot is complaining. Some how this seems related to fact that the entire documentation disappeared. Hope to be able to solve this soon.

**Comment by joa-quim** [comment]
Real strange. Something deleted all the old versions of the documentation and now it reappeared the *latest* but under the name of *dev*. Fixed the link and it works again but WTF!!!!

**Comment by joa-quim** [comment]
OK, I'm closing this as the situations has been solved.

**Comment by ali-ramadhan** [comment]
Thank you! Yeah looks like the `gh-pages` branch got nuked 😱 Super weird...

**Comment by joa-quim** [comment]
Yes, I has github unicorns showing up (instead of 404's) some days before. Looks like they were the ones blowing it.
