### ISSUE TITLE
API not defined

### ISSUE THREAD

**Issue by barthelemymp** [GenericMappingTools/GMT.jl#561]
Hello I am working on julia trying to use the GMT wrapper. I am on windows. I have installed GMT in "C:\\programs\\gmt6\\bin", and this is in the PATH of the system. I installed GMT.jl, but it does not work.
`test GMT ` gives me
```
test GMT
    Testing GMT
Status `C:\Users\bartm\AppData\Local\Temp\jl_Ny2yPm\Project.toml`
  [5752ebe1] GMT v0.30.1
  [ade2ca70] Dates
  [de0858da] Printf
  [10745b16] Statistics
  [8dfed614] Test
Status `C:\Users\bartm\AppData\Local\Temp\jl_Ny2yPm\Manifest.toml`
  [5752ebe1] GMT v0.30.1
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [b77e0a4c] InteractiveUtils
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [de0858da] Printf
  [9a3f8284] Random
  [9e88b42a] Serialization
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [8dfed614] Test
  [4ec0a83e] Unicode


You don't seem to have GMT installed and I don't install it automatically.
You will have to do it yourself.
Download and install the official version at (the '..._win64.exe':
                 https://github.com/GenericMappingTools/gmt/releases
ERROR: LoadError: UndefVarError: Gdal not defined
Stacktrace:
 [1] include(::String) at .\client.jl:457
 [2] top-level scope at none:6
in expression starting at C:\Users\bartm\.julia\packages\GMT\zIejk\test\runtests.jl:1
ERROR: Package GMT errored during testing
```

as found on forums I tried 
```
using Libdl
push!(Libdl.DL_LOAD_PATH, "C:\\programs\\gmt6\\bin")
```
but it does not change the problem... 
Any idea ?

Best Barthelemy

**Comment by joa-quim** [comment]
Hi @barthelemymp, sorry for this little hiccup in using GMT.jl but we are going to solve it easily (I hope).

My guess: your GMT installation is not in Windows PATH. That happens when your path is already long and a stupidly old bug in the NSIS installer (out of our control) did not add the  ``C:\programs\gmt6\bin`` to Windows path (but you should have gotten a message warning about this).

Solution: add ``C:\programs\gmt6\bin`` to Windows path (tell us if you have doubts on this step).

**Comment by barthelemymp** [comment]
Hello joa-quim, 

Thank you for your reply. Unfortunately `C:\programs\gmt6\bin` is already in the system path. Maybe I should precise that I use julia in juno, with a specific environment. ( I start by doing `activate Myenv ` in the Repl before doing anything)

Thank you again

**Comment by joa-quim** [comment]
OK, so you should try from a regular REPL. I don't know what ``activate Myenv`` does but if it changes the path and hides ``C:\programs\gmt6\bin`` then that would explain why it doesn't (and can't) work.
``GMT.jl`` is all developed on Windows so here is where it is more tested.
