### ISSUE TITLE
imshow: Catch user trying to apply a CPT to an image

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/GMT.jl#574]
Catch user trying to apply a CPT to an image and issue a meaningful error-message. See [forum](https://forum.generic-mapping-tools.org/t/gmt-jl-how-to-use-a-cpt-with-imshow/1571) for context.

`imshow(G3, fmt=:png, color="faa.cpt")`

Currently only throws 

`Warning: the following options were not consumed in grdimage => [:color]`

**Comment by joa-quim** [comment]
Fixed by #576. It now prints
```
Warning: You are possibly asking to assign a CPT to an image. That is not allowed by GMT. See function image_cpt!
```
but I'll live this issue open because the recommended solution is still broken and not obvious to find out why.
