### ISSUE TITLE
modern mode does not crop pdf

### ISSUE THREAD

**Issue by htyeim** [GenericMappingTools/GMT.jl#629]
The new version of GMT.jl (or gmt) does not crop pdf and can not output png...
Example shows below:
## pdf
the code is modified from [www.generic-mapping-tools.org/GMT.jl/dev](https://www.generic-mapping-tools.org/GMT.jl/dev/gallery/scripts_agu/histo_step/)

```

function test_gmt1()
    D1 = histogram(randn(1000), I=:o, bin=0.1);
    gmtbegin()
    gmtfig("test_gmt", fmt="pdf")
    lines(D1,  steps=(x = true,), close=(bot = "",), 
            fill=(pattern = 20, 
            bg = :green, dpi = 200), 
            figsize=(15, 10))
    gmtend()

end
@time test_gmt1()
  0.116227 seconds (634 allocations: 52.359 KiB)

```
The output file is [test_gmt.pdf](https://github.com/GenericMappingTools/GMT.jl/files/6653224/test_gmt.pdf). The figure is on the left bottom of the file. I think the pdf wasn't crop after output. Is it necessary to pass some parameters to crop the output file?

## png
If I change `pdf` to `png`, then the program needs more computation recourse and more time to exxcute... but the result png file cann't be opened...

```function test_gmt2()

    D1 = histogram(randn(1000), I=:o, bin=0.1);
    gmtbegin()
    gmtfig("test_gmt", fmt="png")
    lines(D1,  steps=(x = true,), close=(bot = "",), 
            fill=(pattern = 20, 
            bg = :green, dpi = 200), 
            figsize=(15, 10))
    gmtend()

end
@time test_gmt2()
  119.192145 seconds (634 allocations: 52.359 KiB)
```
During the execution, there was a gs process whose cpu usage was around 100%...

I don't know if it is caused by some modify of internal logical of `GMT.jl`?

EDIT:
Even in Archlinux (with gmt 6.1.1), the output pdf isn't crop as well..

**Comment by joa-quim** [comment]
Yes, things changed in version 0.32 to make ``png`` the default format because with the default in postscript it was not possible to make plots larger than A4 and have been doing lots of plots and it works fine. But I suspect that in your case it is a ghostscript related issue. If you have a pdf figure it's because everything worked, except the crop. The crop is done by the option **-A1p** in the line
```
gmt("psconvert -A1p -Qg4 -Qt4 " * fname_ps * opt_T * " *")
```
of the *showfig* function in the ``common_options.jl`` file. I don't see how it can fail but apparently it did. That instruction is equivalent in running on a shell the command
```
psconvert /tmp/GMTjl_tmp.ps -A1p -Qg4 -Qt4 -Tf
```

**Comment by joa-quim** [comment]
Ah, you are right I can reproduce it. The problem is that almost never use the GMT modern mode and so this has not been tested. You example works if I turn it a classic mode
```
D1 = histogram(randn(1000), I=:o, bin=0.1);
lines(D1, steps=(x=true,), close=(bot="",), fill=(pattern=20, bg=:green, dpi=200), figsize=(15, 10), show=true)
```

Note sure on my time disponibility to fix this

**Comment by joa-quim** [comment]
Probably this issue existed all the time but was hidden until I made the default format change. What happens is that in modern mode it's GMT itself that does the cropping (not via a GMT.jl call). And for some reason it's not doing it if it detects a page size change (or something around this). If you set in the Julia REPL ``GMT.FMT[1] = "ps";`` or set an environment variable ``JULIA_GMT_IMGFORMAT=ps``, to make it permanent, then you should be back to the previous situation and cropping works (but classic scripts won't be able to have figs > A4). Not fully satisfactory but this issue will require a lot of digging.

**Comment by joa-quim** [comment]
It turns out the solution is pretty simple. Should be fixed in master.

**Comment by htyeim** [comment]
Thank you! The problem has been solved.

I use only modern mode 😆 I need to find something to identify the thing I try to plot/change. When I used python, I always wrote `fig = plt.figure()` first [ref](https://www.tutorialspoint.com/tutorial_view.php?cid=matplotlib&pid=matplotlib_object_oriented_interface.htm). When I use `GMT.jl`, I want `gmtbegin()` first also.
