### ISSUE TITLE
Is there a way to inspect the final GMT command?

### ISSUE THREAD

**Issue by adigitoleo** [GenericMappingTools/GMT.jl#663]
I believe this package works by building a GMT command and using the gmt binary to run it, correct? If so, is there a way to view the command that has been built (ideally from within the julia shell)? I'm new to GMT so I find myself cross-referencing the GMT docs frequently, but I can't always predict what my julia command actually corresponds to (and I want to avoid the cryptic gmt syntax if possible).

I understand that writing the whole documentation for the bindings will be a big task, so having this option will help me to use the existing GMT docs as well in the meantime.

**Comment by joa-quim** [comment]
Yes, you are right. It generates GMT commands that do the job. And what you are asking exists as I needed badly too.
All the commands accept the option **Vd**. If **Vd=1** it will print the generated command and execute it. **Vd=2** only prints and doesn't run it. Furthermore, there is also a command, ``gmthelp`` that shows the mapping between the GMT single letter options and the GMT.jl syntax. It's far from perfect but let us do for example

```
julia> gmthelp(grdtrack)
Option: R, or V_params, or bi, or bo, or di, or e, or f, or g, or h, or i, or n, or o, or s, or yx => (Common options)
Option: A, or interp_path => Tuple | String | Number | Bool [Possibly not yet expanded]
Option: C, or equidistant => Tuple | String | Number | Bool [Possibly not yet expanded]
Option: D, or dfile => Tuple | String | Number | Bool [Possibly not yet expanded]
Option: E, or by_coord => Tuple | String | Number | Bool [Possibly not yet expanded]
Option: N, or no_skip => Tuple | String | Number | Bool [Possibly not yet expanded]
Option: S, or stack => Tuple | String | Number | Bool [Possibly not yet expanded]
Option: T, or radius => Tuple | String | Number | Bool [Possibly not yet expanded]
Option: Z, or z_only => Tuple | String | Number | Bool [Possibly not yet expanded]
Option: G, or grid => GMTgrid | Tuple | String

julia> gmthelp(:R)
Option: R, or region, or limits => GMTgrid | NamedTuple |Tuple | Array | String
```

**Comment by adigitoleo** [comment]
Thanks, @joa-quim , I knew about gmthelp but not Vd, this will be helpful. I'm currently working on translating some of the GMT tutorial examples into julia in my free time. If I get enough of them done, I might upload it somewhere or open a PR to add it in the docs, but I can't promise anything yet!

I will close this issue. I have one more question, but I understand that you might not be able to help... The problem that I currently want to solve the most is plotting vectors (actually shear-wave splitting bars, like in [this plot](https://www.iris.edu/gallery3/var/albums/research/2010proposal/lithosphere/Fig6_all_splits.jpg?m=1400096509)) on top of a map using the correct projection. If you know of a GMT(.jl) example with even a basic version of this (single `arrow` on a Mercator map, specified by midpoint and angle?) that would be really awesome. But I'll keep learning GMT and maybe I'll work it out :)

**Comment by joa-quim** [comment]
Thanks, tutorials and more examples will be most appreciated but take your time

Regarding the plot, I think it was made using rotated rectangles (because they have a fill and an outline), See option ``-Sjdirection/width/height`` in ``plot``
