### ISSUE TITLE
[Bug Report] Failed to precompile on Windows

### ISSUE THREAD

**Issue by yezhengkai** [GenericMappingTools/GMT.jl#712]
# Description
When use `pkg> add GMT` on Windows, the Windows installer successfully installed GMT, but when GMT.jl was precompiled, the console displayed the following error message.
![image](https://user-images.githubusercontent.com/19803045/136176558-14d13ce1-a975-46be-a72a-3bdb255a7332.png)

# Solution
I found that the path of _libgmt in `deps.jl` is `"C:/programs/gmt6/bin/gmt_w64.dll"`, and when I change the path to `"C:\\programs\\gmt6\\bin\\gmt_w64.dll"` GMT.jl can be precompiled smoothly.

I think the bug comes from this
https://github.com/GenericMappingTools/GMT.jl/blob/d14195e451913cfeece1cb5b5f15f3048f14070b/deps/build.jl#L22

And we might be able to fix this bug by using `abspath` instead of `string`
```julia
libgmt = abspath(chop(read(`$(joinpath("$(GMT_bindir)", "gmt")) --show-library`, String)))
```

**Comment by joa-quim** [comment]
Good. I don't understand hat happened but if that helps you and others that may have the same issue, I've added ``abspath`` in #713.
Thanks for reporting and digging.
