### ISSUE TITLE
Trouble with installing GMT with Julia

### ISSUE THREAD

**Issue by LucasEskens** [GenericMappingTools/GMT.jl#722]
Hello, I'm quite new to working with Julia. Currently I'm trying to GMT to work with Julia, however I have the idea that
the wrapper is not working for me properly. Using the command "using GMT" seems to work fine, however anything afterwards involving GMT isn't working, see the example below.

![github error](https://user-images.githubusercontent.com/92924638/138268459-d1aa84f4-9ff7-4bbb-af9e-f1752f7f02d8.png)

Does anyone have an idea how I could solve this issue? I'm working on Windows, which I think influences the workflow.

**Comment by joa-quim** [comment]
> I'm working on Windows, which I think influences the workflow.

Yes it does, it makes it work better 😃
