### ISSUE TITLE
Conflicting with the MAT.jl and NCDatasets.jl packages

### ISSUE THREAD

**Issue by Leon6j** [GenericMappingTools/GMT.jl#737]
According to the error message, the reason seems to be “Incompatible library version: libgdal.29.dylib requires version 202.0.0 or later, but libhdf5.200.dylib provides version 201.0.0”.

Please see this thread for more details: https://discourse.julialang.org/t/does-the-gmt-jl-package-conflict-with-the-mat-jl-and-ncdatasets-jl-packages/70639/6

**Comment by joa-quim** [comment]
Not really our fault. That's life on unix.
