### ISSUE TITLE
Link for Ghostscript and ghostview in Readme.md is broken

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/GMT.jl#825]
The link in the following line is broken. I don't know which is the correct one. 

> Install Ghostscript and ghostview at https://www.ghostscript.com/download/gsdnld.html

**Comment by Esteban82** [comment]
Is it this??  
https://ghostscript.com/releases/gsdnld.html

**Comment by joa-quim** [comment]
Thanks, I've updated the link. The temptation to change seems irresistible.
