### ISSUE TITLE
Local gmt.conf file not being used?

### ISSUE THREAD

**Issue by adigitoleo** [GenericMappingTools/GMT.jl#828]
It seems like the `gmt.conf` file in the local directory is not being used. The commands below all plot a figure with the same title font for me:

```
julia> gmtset(FONT_TITLE = "2p,Helvetica,black")

julia> coast(region = (110, 210, -35, 45), proj = :Mercator, frame = :auto, land = :dimgray, title = "Test title font customization")

julia> showfig()

shell> grep 'FONT_TITLE' gmt.conf
FONT_TITLE                     = 2p,Helvetica,black

julia> coast(region = (110, 210, -35, 45), proj = :Mercator, frame = :auto, land = :dimgray, title = "Test title font customization")

julia> showfig()

julia> gmtset(FONT_TITLE = "50p,Helvetica,black")

julia> coast(region = (110, 210, -35, 45), proj = :Mercator, frame = :auto, land = :dimgray, title = "Test title font customization")

julia> showfig()

shell> grep 'FONT_TITLE' gmt.conf
FONT_TITLE                     = 50p,Helvetica,black
```

The `gmtset` commands are working, because the file is being created/modified. However, the settings are not being used. I tried changing the global gmt.conf and it seems to work, so I think it's just using that one always.

**Comment by joa-quim** [comment]
Yes, it was not. Made some changes and now it never is by design (to not interfere with next plot in day after) but ``gmtset()`` now immediately applies the setting directly to the API.
